CREATE TABLE titles (
  id INT AUTO_INCREMENT,
  title VARCHAR(255),
  releaseDate DATE,
  rating VARCHAR(255),
  runTime INT
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt DATETIME,
  PRIMARY KEY(id)
  FOREIGN KEY(directorId)
  FOREIGN KEY(genreId)
);
